### ISSUE TITLE
include nav changes in the exclude filter?

### ISSUE THREAD

**Issue by DutchessNicole** [apenwarr/mkdocs-exclude#1]
Currently, the plugin correcly globs the directories that I want excluded from a build.
Would it also be possible to have it exclude those same patterns from the nav section?

For instance, say I have a yaml like so:

```
nav:
  path_a: 
    file1: path_a/file.md
    file2: path_a/file2.md
  path_b:
    file3: path_b/file.md
    file4: path_b/file2.md
```
with the associated exclude mapping
```
exclude:
  - glob:
      - path_b*
```

Then the plugin will correctly filter out the actual path items, but it will still leave the navigation menu intact.

Ideally any paths that also match the patterns in the nav section (and their parents, if they end up being empty) would also be removed. 

This way we don't end up with a menu full of dangling links to files that don't exist.

Thanks for the plugin!
